// prisma/seed.ts
import { prisma } from '../src/lib/prisma'

/**
 * 25 realistic physicians distributed across 10 major US health systems.
 * Specialty distribution: Oncology(6), Cardiology(5), Neurology(4),
 * Rheumatology(3), Endocrinology(3), Gastroenterology(4).
 * ~60% have a subSpecialty, 80% acceptingPatients, 90% boardCertified.
 */
const PHYSICIANS = [
  // ── Oncology (6) ───────────────────────────────────────────────────────────
  {
    npi: '1487263940',
    firstName: 'Sarah',
    lastName: 'Chen',
    specialty: 'Oncology',
    subSpecialty: 'Breast Oncology',
    affiliation: 'Johns Hopkins Hospital',
    city: 'Baltimore',
    state: 'MD',
    email: 'sarah.chen@jhmi.edu',
    npiRegistrationYear: 2008,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1639285710',
    firstName: 'James',
    lastName: 'Rodriguez',
    specialty: 'Oncology',
    subSpecialty: 'Thoracic Oncology',
    affiliation: 'MD Anderson Cancer Center',
    city: 'Houston',
    state: 'TX',
    email: 'james.rodriguez@mdanderson.org',
    npiRegistrationYear: 2005,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1852047361',
    firstName: 'Michael',
    lastName: 'Torres',
    specialty: 'Oncology',
    subSpecialty: null,
    affiliation: 'Mayo Clinic',
    city: 'Rochester',
    state: 'MN',
    email: 'michael.torres@mayo.edu',
    npiRegistrationYear: 2003,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1047283659',
    firstName: 'Lisa',
    lastName: 'Kim',
    specialty: 'Oncology',
    subSpecialty: 'Gynecologic Oncology',
    affiliation: 'Massachusetts General Hospital',
    city: 'Boston',
    state: 'MA',
    email: 'lisa.kim@mgh.harvard.edu',
    npiRegistrationYear: 2012,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1372940185',
    firstName: 'Priya',
    lastName: 'Patel',
    specialty: 'Oncology',
    subSpecialty: 'Hematologic Oncology',
    affiliation: 'UCSF Medical Center',
    city: 'San Francisco',
    state: 'CA',
    email: 'priya.patel@ucsf.edu',
    npiRegistrationYear: 2010,
    acceptingPatients: false,
    boardCertified: true,
  },
  {
    npi: '1295837461',
    firstName: 'David',
    lastName: 'Washington',
    specialty: 'Oncology',
    subSpecialty: 'Neuro-Oncology',
    affiliation: 'Mount Sinai Hospital',
    city: 'New York',
    state: 'NY',
    email: 'david.washington@mountsinai.org',
    npiRegistrationYear: 2007,
    acceptingPatients: false,
    boardCertified: true,
  },

  // ── Cardiology (5) ─────────────────────────────────────────────────────────
  {
    npi: '1748205936',
    firstName: 'Robert',
    lastName: 'Martinez',
    specialty: 'Cardiology',
    subSpecialty: 'Interventional Cardiology',
    affiliation: 'Cleveland Clinic',
    city: 'Cleveland',
    state: 'OH',
    email: 'robert.martinez@ccf.org',
    npiRegistrationYear: 2004,
    acceptingPatients: false,
    boardCertified: true,
  },
  {
    npi: '1039274658',
    firstName: 'Jennifer',
    lastName: 'Lee',
    specialty: 'Cardiology',
    subSpecialty: null,
    affiliation: 'Northwestern Memorial Hospital',
    city: 'Chicago',
    state: 'IL',
    email: 'jennifer.lee@nm.org',
    npiRegistrationYear: 2009,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1584729036',
    firstName: 'William',
    lastName: 'Johnson',
    specialty: 'Cardiology',
    subSpecialty: null,
    affiliation: 'Mayo Clinic',
    city: 'Rochester',
    state: 'MN',
    email: 'william.johnson@mayo.edu',
    npiRegistrationYear: 2001,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1263748590',
    firstName: 'Angela',
    lastName: 'Davis',
    specialty: 'Cardiology',
    subSpecialty: 'Electrophysiology',
    affiliation: 'Johns Hopkins Hospital',
    city: 'Baltimore',
    state: 'MD',
    email: 'angela.davis@jhmi.edu',
    npiRegistrationYear: 2011,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1937402856',
    firstName: 'Thomas',
    lastName: 'Nguyen',
    specialty: 'Cardiology',
    subSpecialty: 'Structural Heart Disease',
    affiliation: 'NYU Langone Health',
    city: 'New York',
    state: 'NY',
    email: 'thomas.nguyen@nyulangone.org',
    npiRegistrationYear: 2006,
    acceptingPatients: true,
    boardCertified: true,
  },

  // ── Neurology (4) ──────────────────────────────────────────────────────────
  {
    npi: '1403928571',
    firstName: 'Rachel',
    lastName: 'Cohen',
    specialty: 'Neurology',
    subSpecialty: 'Movement Disorders',
    affiliation: 'Massachusetts General Hospital',
    city: 'Boston',
    state: 'MA',
    email: 'rachel.cohen@mgh.harvard.edu',
    npiRegistrationYear: 2013,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1726405839',
    firstName: 'Kevin',
    lastName: 'Park',
    specialty: 'Neurology',
    subSpecialty: 'Epilepsy',
    affiliation: 'Duke University Hospital',
    city: 'Durham',
    state: 'NC',
    email: 'kevin.park@duke.edu',
    npiRegistrationYear: 2002,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1058234967',
    firstName: 'Stephanie',
    lastName: 'Wilson',
    specialty: 'Neurology',
    subSpecialty: null,
    affiliation: 'NYU Langone Health',
    city: 'New York',
    state: 'NY',
    email: 'stephanie.wilson@nyulangone.org',
    npiRegistrationYear: 2015,
    acceptingPatients: true,
    boardCertified: false,
  },
  {
    npi: '1834605720',
    firstName: 'Brian',
    lastName: 'Okafor',
    specialty: 'Neurology',
    subSpecialty: 'Multiple Sclerosis',
    affiliation: 'UCSF Medical Center',
    city: 'San Francisco',
    state: 'CA',
    email: 'brian.okafor@ucsf.edu',
    npiRegistrationYear: 2008,
    acceptingPatients: true,
    boardCertified: true,
  },

  // ── Rheumatology (3) ───────────────────────────────────────────────────────
  {
    npi: '1629475038',
    firstName: 'Patricia',
    lastName: 'Murphy',
    specialty: 'Rheumatology',
    subSpecialty: 'Autoimmune Disease',
    affiliation: 'Johns Hopkins Hospital',
    city: 'Baltimore',
    state: 'MD',
    email: 'patricia.murphy@jhmi.edu',
    npiRegistrationYear: 2000,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1473820596',
    firstName: 'Carlos',
    lastName: 'Hernandez',
    specialty: 'Rheumatology',
    subSpecialty: null,
    affiliation: 'Massachusetts General Hospital',
    city: 'Boston',
    state: 'MA',
    email: 'carlos.hernandez@mgh.harvard.edu',
    npiRegistrationYear: 2014,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1246378905',
    firstName: 'Nancy',
    lastName: 'Liu',
    specialty: 'Rheumatology',
    subSpecialty: 'Inflammatory Arthritis',
    affiliation: 'Northwestern Memorial Hospital',
    city: 'Chicago',
    state: 'IL',
    email: 'nancy.liu@nm.org',
    npiRegistrationYear: 2007,
    acceptingPatients: true,
    boardCertified: true,
  },

  // ── Endocrinology (3) ──────────────────────────────────────────────────────
  {
    npi: '1893047256',
    firstName: 'Mark',
    lastName: 'Thompson',
    specialty: 'Endocrinology',
    subSpecialty: null,
    affiliation: 'Mayo Clinic',
    city: 'Rochester',
    state: 'MN',
    email: 'mark.thompson@mayo.edu',
    npiRegistrationYear: 1999,
    acceptingPatients: false,
    boardCertified: true,
  },
  {
    npi: '1530274869',
    firstName: 'Olivia',
    lastName: 'Brown',
    specialty: 'Endocrinology',
    subSpecialty: null,
    affiliation: 'Duke University Hospital',
    city: 'Durham',
    state: 'NC',
    email: 'olivia.brown@duke.edu',
    npiRegistrationYear: 2016,
    acceptingPatients: true,
    boardCertified: false,
  },
  {
    npi: '1672093845',
    firstName: 'Steven',
    lastName: 'Chang',
    specialty: 'Endocrinology',
    subSpecialty: 'Thyroid Disorders',
    affiliation: 'Cleveland Clinic',
    city: 'Cleveland',
    state: 'OH',
    email: 'steven.chang@ccf.org',
    npiRegistrationYear: 2010,
    acceptingPatients: true,
    boardCertified: true,
  },

  // ── Gastroenterology (4) ───────────────────────────────────────────────────
  {
    npi: '1358204976',
    firstName: 'Amanda',
    lastName: 'Foster',
    specialty: 'Gastroenterology',
    subSpecialty: null,
    affiliation: 'Mount Sinai Hospital',
    city: 'New York',
    state: 'NY',
    email: 'amanda.foster@mountsinai.org',
    npiRegistrationYear: 2011,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1904736258',
    firstName: 'Daniel',
    lastName: 'Kim',
    specialty: 'Gastroenterology',
    subSpecialty: null,
    affiliation: 'MD Anderson Cancer Center',
    city: 'Houston',
    state: 'TX',
    email: 'daniel.kim@mdanderson.org',
    npiRegistrationYear: 2005,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1437850629',
    firstName: 'Helen',
    lastName: 'Walsh',
    specialty: 'Gastroenterology',
    subSpecialty: 'Hepatology & Liver Disease',
    affiliation: 'NYU Langone Health',
    city: 'New York',
    state: 'NY',
    email: 'helen.walsh@nyulangone.org',
    npiRegistrationYear: 2009,
    acceptingPatients: true,
    boardCertified: true,
  },
  {
    npi: '1860392475',
    firstName: 'Christopher',
    lastName: 'Reed',
    specialty: 'Gastroenterology',
    subSpecialty: null,
    affiliation: 'Duke University Hospital',
    city: 'Durham',
    state: 'NC',
    email: 'christopher.reed@duke.edu',
    npiRegistrationYear: 2003,
    acceptingPatients: false,
    boardCertified: true,
  },
]

async function main() {
  console.log(`Seeding ${PHYSICIANS.length} physicians...`)

  for (const data of PHYSICIANS) {
    const physician = await prisma.physician.upsert({
      where: { npi: data.npi },
      update: {},   // idempotent: skip updates if record already exists
      create: data,
    })
    console.log(`  ✓ Dr. ${physician.firstName} ${physician.lastName} (${physician.specialty})`)
  }

  const total = await prisma.physician.count()
  console.log(`\nSeed complete. ${total} physicians in database.`)
}

main()
  .catch((err) => {
    console.error('Seed failed:', err)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
